import bcrypt from 'bcryptjs';

export async function getSeedData() {
  const passwordHash = await bcrypt.hash('Admin@123', 10);
  const facultyHash = await bcrypt.hash('Faculty@123', 10);

  const users = [
    {
      name: 'Dr. Rajesh Sharma',
      email: 'admin@campussynapse.edu',
      passwordHash,
      role: 'SUPER_ADMIN',
      department: 'Central Administration',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    },
    {
      name: 'Prof. Ananya Sen',
      email: 'campusadmin@campussynapse.edu',
      passwordHash,
      role: 'CAMPUS_ADMIN',
      department: 'Academic Operations',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    },
    {
      name: 'Dr. Vikram Patel',
      email: 'faculty@campussynapse.edu',
      passwordHash: facultyHash,
      role: 'FACULTY',
      department: 'Computer Science & Engineering',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    },
    {
      name: 'Rohan Verma',
      email: 'student@campussynapse.edu',
      passwordHash: facultyHash,
      role: 'STUDENT',
      department: 'Computer Science & Engineering',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    },
    {
      name: 'Suresh Kumar',
      email: 'staff@campussynapse.edu',
      passwordHash: facultyHash,
      role: 'FACILITY_STAFF',
      department: 'Campus Facilities & Maintenance',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    },
  ];

  const buildings = [
    {
      name: 'Block A (Engineering & Physical Sciences)',
      code: 'BLDG-A',
      totalFloors: 4,
      departments: ['Mechanical', 'Civil', 'Electrical Engineering'],
      totalRooms: 8,
      description: 'Houses heavy laboratories, fabrication units, and engineering lecture halls.',
    },
    {
      name: 'Block B (Main Academic & Seminar Complex)',
      code: 'BLDG-B',
      totalFloors: 4,
      departments: ['Computer Science', 'Information Technology', 'Humanities'],
      totalRooms: 10,
      description: 'Central campus academic spine with high-capacity seminar halls and smart classrooms.',
    },
    {
      name: 'Block C (Advanced Computing & Performing Arts)',
      code: 'BLDG-C',
      totalFloors: 3,
      departments: ['AI & Data Science', 'Biotech', 'Media Studies'],
      totalRooms: 8,
      description: 'Equipped with High Performance Computing labs, Main Auditorium, and Media studios.',
    },
  ];

  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  const tomorrowStr = tomorrow.toISOString().split('T')[0];

  const resources = [
    // BLOCK B — Core academic & seminar
    {
      name: 'Auditorium 1 (Rabindranath Tagore Hall)',
      code: 'AUD-B-01',
      type: 'AUDITORIUM',
      capacity: 350,
      status: 'AVAILABLE',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 1,
      location: 'Ground Floor, North Wing',
      equipment: ['Dual Laser Projectors', 'Surround Sound System', 'Podium Mics', 'Stage Lighting', 'Live Stream Rig'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 74,
      nextAvailable: 'Now',
      schedule: [
        {
          bookingId: 'b-aud-morning',
          title: 'Dean Address to Freshers',
          organizer: 'Dean of Student Affairs',
          startTime: '09:30',
          endTime: '12:00',
          attendees: 320,
          status: 'SCHEDULED',
          type: 'EVENT',
        },
      ],
      telemetry: { occupancyCount: 0, temperatureCelsius: 22, powerDrawWatts: 1200, airQualityIndex: 38, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Seminar Hall A (Sir CV Raman Hall)',
      code: 'SEM-B-01',
      type: 'SEMINAR_HALL',
      capacity: 200,
      status: 'AVAILABLE',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 2,
      location: 'Second Floor, Central Atrium',
      equipment: ['Laser Projector', 'Audio System', 'Microphone', 'High-Speed Wi-Fi', 'Smart Podium'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 86,
      nextAvailable: 'Now',
      schedule: [
        // Intentionally placed conflict for 2:30 PM to 4:00 PM tomorrow to trigger hero orchestration!
        {
          bookingId: 'b-sem-conflict',
          title: 'Guest Lecture: Distributed Systems Architecture',
          organizer: 'Dr. Vikram Patel',
          startTime: '14:30',
          endTime: '16:00',
          attendees: 160,
          status: 'SCHEDULED',
          type: 'CLASS',
        },
      ],
      telemetry: { occupancyCount: 0, temperatureCelsius: 23, powerDrawWatts: 850, airQualityIndex: 42, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Seminar Hall B (Homi Bhabha Hall)',
      code: 'SEM-B-02',
      type: 'SEMINAR_HALL',
      capacity: 190,
      status: 'AVAILABLE',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 2,
      location: 'Second Floor, South Wing',
      equipment: ['Laser Projector', 'Audio System', 'Microphone', 'High-Speed Wi-Fi', 'Motorized Screen'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 88,
      nextAvailable: 'Now (Open All Afternoon)',
      schedule: [
        {
          bookingId: 'b-sem-b-morn',
          title: 'Department Faculty Council Meeting',
          organizer: 'Prof. Mukherjee',
          startTime: '10:00',
          endTime: '12:30',
          attendees: 45,
          status: 'SCHEDULED',
          type: 'MEETING',
        },
      ],
      telemetry: { occupancyCount: 0, temperatureCelsius: 22, powerDrawWatts: 620, airQualityIndex: 40, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom B201',
      code: 'RM-B-201',
      type: 'CLASSROOM',
      capacity: 70,
      status: 'OCCUPIED',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 2,
      location: 'Second Floor, Room 201',
      equipment: ['Smart Board', 'Ceiling Projector', 'Whiteboard', 'Air Conditioner'],
      accessibility: true,
      currentOccupancy: 62,
      utilizationRate: 91,
      nextAvailable: '14:00',
      schedule: [
        {
          bookingId: 'b-201-1',
          title: 'Operating Systems (CS301)',
          organizer: 'Dr. Vikram Patel',
          startTime: '11:00',
          endTime: '13:00',
          attendees: 65,
          status: 'IN_PROGRESS',
          type: 'CLASS',
        },
      ],
      telemetry: { occupancyCount: 62, temperatureCelsius: 24, powerDrawWatts: 710, airQualityIndex: 48, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom B204 (Ghost Booking - Unused)',
      code: 'RM-B-204',
      type: 'CLASSROOM',
      capacity: 60,
      status: 'RESERVED',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 2,
      location: 'Second Floor, Room 204',
      equipment: ['Ceiling Projector', 'Whiteboard', 'Sound Bar'],
      accessibility: true,
      currentOccupancy: 0, // Telemetry confirms ghost reservation!
      utilizationRate: 45,
      nextAvailable: 'Reserved (Grace Period Expired)',
      schedule: [
        {
          bookingId: 'b-204-ghost',
          title: 'Robotics Club Internal Discussion',
          organizer: 'Student Council Rep',
          startTime: '11:00',
          endTime: '13:00',
          attendees: 45,
          status: 'SCHEDULED',
          type: 'MEETING',
        },
      ],
      telemetry: { occupancyCount: 0, temperatureCelsius: 21, powerDrawWatts: 210, airQualityIndex: 35, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom B102',
      code: 'RM-B-102',
      type: 'CLASSROOM',
      capacity: 65,
      status: 'AVAILABLE',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 1,
      location: 'First Floor, Room 102',
      equipment: ['Smart Board', 'Whiteboard', 'Audio System'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 78,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 22, powerDrawWatts: 300, airQualityIndex: 39, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom B103',
      code: 'RM-B-103',
      type: 'CLASSROOM',
      capacity: 65,
      status: 'AVAILABLE',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 1,
      location: 'First Floor, Room 103',
      equipment: ['Projector', 'Whiteboard'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 70,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 22, powerDrawWatts: 320, airQualityIndex: 40, lastPingTime: new Date().toISOString() },
    },
    // BLOCK C — Computing & High Capacity
    {
      name: 'Auditorium 2 (Vikram Sarabhai Grand Theater)',
      code: 'AUD-C-01',
      type: 'AUDITORIUM',
      capacity: 500,
      status: 'AVAILABLE',
      buildingId: 'BLDG-C',
      buildingName: 'Block C (Advanced Computing & Performing Arts)',
      floor: 1,
      location: 'Block C Ground Concourse',
      equipment: ['Dual 4K Laser Projectors', 'Line Array Audio', 'Telepresence Suite', 'Stage Rigging'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 68,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 21, powerDrawWatts: 1400, airQualityIndex: 36, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Advanced Computing Lab C1',
      code: 'LAB-C-01',
      type: 'LABORATORY',
      capacity: 80,
      status: 'MAINTENANCE',
      buildingId: 'BLDG-C',
      buildingName: 'Block C (Advanced Computing & Performing Arts)',
      floor: 2,
      location: 'Second Floor, Lab Wing C',
      equipment: ['80 GPU Workstations', 'Optical Fiber Switches', 'Ceiling AC Unit'],
      accessibility: true,
      maintenanceState: {
        isUnderMaintenance: true,
        issue: 'Electrical panel intermittent sparking reported on circuit breaker 4B',
        priority: 'CRITICAL',
        ticketId: 'TICK-9082',
      },
      currentOccupancy: 0,
      utilizationRate: 52,
      nextAvailable: 'Under Safety Inspection',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 27, powerDrawWatts: 50, airQualityIndex: 55, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'AI Research Lab C2',
      code: 'LAB-C-02',
      type: 'LABORATORY',
      capacity: 75,
      status: 'OCCUPIED',
      buildingId: 'BLDG-C',
      buildingName: 'Block C (Advanced Computing & Performing Arts)',
      floor: 2,
      location: 'Second Floor, Lab Wing C',
      equipment: ['75 High-Spec PCs', 'Smart Display Wall', 'Soundproofing'],
      accessibility: true,
      currentOccupancy: 68,
      utilizationRate: 94,
      nextAvailable: '16:30',
      schedule: [
        {
          bookingId: 'b-lab-c2-1',
          title: 'Deep Learning Workshop Practicum',
          organizer: 'Dr. Meera Nambiar',
          startTime: '13:00',
          endTime: '16:30',
          attendees: 70,
          status: 'IN_PROGRESS',
          type: 'LAB',
        },
      ],
      telemetry: { occupancyCount: 68, temperatureCelsius: 20, powerDrawWatts: 3800, airQualityIndex: 44, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom C301',
      code: 'RM-C-301',
      type: 'CLASSROOM',
      capacity: 70,
      status: 'AVAILABLE',
      buildingId: 'BLDG-C',
      buildingName: 'Block C (Advanced Computing & Performing Arts)',
      floor: 3,
      location: 'Third Floor, Room 301',
      equipment: ['Laser Projector', 'Interactive Whiteboard'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 72,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 23, powerDrawWatts: 340, airQualityIndex: 41, lastPingTime: new Date().toISOString() },
    },
    // BLOCK A — Engineering
    {
      name: 'Robotics & Automation Lab A1',
      code: 'LAB-A-01',
      type: 'LABORATORY',
      capacity: 50,
      status: 'AVAILABLE',
      buildingId: 'BLDG-A',
      buildingName: 'Block A (Engineering & Physical Sciences)',
      floor: 1,
      location: 'Ground Floor, Heavy Labs Wing',
      equipment: ['Robotic Arms', '3D Printers', 'Oscilloscopes', 'Safety Eye Wash'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 81,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 22, powerDrawWatts: 920, airQualityIndex: 42, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom A101',
      code: 'RM-A-101',
      type: 'CLASSROOM',
      capacity: 60,
      status: 'AVAILABLE',
      buildingId: 'BLDG-A',
      buildingName: 'Block A (Engineering & Physical Sciences)',
      floor: 1,
      location: 'First Floor, Room 101',
      equipment: ['Projector', 'Whiteboard', 'Sound Bar'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 65,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 23, powerDrawWatts: 300, airQualityIndex: 43, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom A102',
      code: 'RM-A-102',
      type: 'CLASSROOM',
      capacity: 60,
      status: 'OCCUPIED',
      buildingId: 'BLDG-A',
      buildingName: 'Block A (Engineering & Physical Sciences)',
      floor: 1,
      location: 'First Floor, Room 102',
      equipment: ['Smart Board', 'Whiteboard'],
      accessibility: true,
      currentOccupancy: 54,
      utilizationRate: 85,
      nextAvailable: '15:00',
      schedule: [
        {
          bookingId: 'b-a102-1',
          title: 'Thermodynamics II',
          organizer: 'Prof. K. R. Nair',
          startTime: '13:00',
          endTime: '15:00',
          attendees: 55,
          status: 'IN_PROGRESS',
          type: 'CLASS',
        },
      ],
      telemetry: { occupancyCount: 54, temperatureCelsius: 24, powerDrawWatts: 680, airQualityIndex: 46, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Classroom A103',
      code: 'RM-A-103',
      type: 'CLASSROOM',
      capacity: 60,
      status: 'AVAILABLE',
      buildingId: 'BLDG-A',
      buildingName: 'Block A (Engineering & Physical Sciences)',
      floor: 1,
      location: 'First Floor, Room 103',
      equipment: ['Projector', 'Whiteboard'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 62,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 23, powerDrawWatts: 280, airQualityIndex: 40, lastPingTime: new Date().toISOString() },
    },
    {
      name: 'Meeting Room B302',
      code: 'MR-B-302',
      type: 'MEETING_ROOM',
      capacity: 18,
      status: 'AVAILABLE',
      buildingId: 'BLDG-B',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      floor: 3,
      location: 'Third Floor, Admin Suite',
      equipment: ['Conference Display 75"', 'Omni Microphone', 'Video Conference Cam'],
      accessibility: true,
      currentOccupancy: 0,
      utilizationRate: 77,
      nextAvailable: 'Now',
      schedule: [],
      telemetry: { occupancyCount: 0, temperatureCelsius: 22, powerDrawWatts: 210, airQualityIndex: 37, lastPingTime: new Date().toISOString() },
    },
  ];

  const maintenanceTickets = [
    {
      ticketNumber: 'TICK-9082',
      title: 'Electrical Panel Sparking in Lab C1',
      description: 'Electrical panel intermittent sparking reported on circuit breaker 4B behind row 4.',
      category: 'ELECTRICAL',
      subcategory: 'High Voltage Hazard',
      priority: 'CRITICAL',
      status: 'IN_PROGRESS',
      resourceId: 'LAB-C-01',
      resourceName: 'Advanced Computing Lab C1',
      buildingName: 'Block C (Advanced Computing & Performing Arts)',
      assignedTeam: 'Emergency Electrical Response Team',
      reportedBy: 'Lab Technician R. Ramesh',
      immediateActionTaken: 'Circuit breaker 4B isolated. Lab C1 status set to MAINTENANCE lock.',
      isEscalated: true,
    },
    {
      ticketNumber: 'TICK-9083',
      title: 'Ceiling Projector Color Distortion',
      description: 'The projector in Room B204 is displaying severe magenta tint and flickering.',
      category: 'EQUIPMENT',
      subcategory: 'AV Hardware Failure',
      priority: 'MEDIUM',
      status: 'REPORTED',
      resourceId: 'RM-B-204',
      resourceName: 'Classroom B204',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      assignedTeam: 'IT / AV Support Services',
      reportedBy: 'Dr. Sen',
      immediateActionTaken: 'Replacement bulb and HDMI filter scheduled.',
      isEscalated: false,
    },
    {
      ticketNumber: 'TICK-9084',
      title: 'HVAC Air Temperature Sensor Failure',
      description: 'Seminar Hall A temperature sensor reporting constant 32°C despite cool air output.',
      category: 'HVAC',
      subcategory: 'Climate Control',
      priority: 'LOW',
      status: 'IN_PROGRESS',
      resourceId: 'SEM-B-01',
      resourceName: 'Seminar Hall A (Sir CV Raman Hall)',
      buildingName: 'Block B (Main Academic & Seminar Complex)',
      assignedTeam: 'HVAC Maintenance Dept',
      reportedBy: 'Facilities Staff',
      immediateActionTaken: 'Thermostat calibration unit dispatched.',
      isEscalated: false,
    },
  ];

  const pendingApprovals = [
    {
      title: 'Annual Tech Symposium: Hackathon Allocations',
      type: 'EVENT_ALLOCATION',
      description: 'Allocation of Seminar Hall B and 3 breakout rooms for 220 attendees on Friday.',
      proposedPlan: {
        planId: 'plan-prop-techsym',
        title: 'Plan A: Seminar Hall B + Lab C2 Breakout',
        resourceId: 'SEM-B-02',
        resourceName: 'Seminar Hall B (Homi Bhabha Hall)',
        buildingName: 'Block B (Main Academic & Seminar Complex)',
        capacity: 190,
        feasibilityScore: 98,
        disruptionScore: 92,
        utilizationScore: 95,
        distanceScore: 90,
        decisionScore: 94.6,
        isRecommended: true,
        recommendationReason: 'Optimized contiguous breakout access and high utilization.',
        reasons: ['Capacity satisfied', 'Zero timetable clashes'],
        tradeOffs: ['Requires 20 extra chairs for peak plenary'],
        requirementsSatisfied: { capacity: true, availability: true, equipment: true, accessibility: true, policyPassed: true },
      },
      requiredRole: 'CAMPUS_ADMIN',
      status: 'PENDING',
      requestedByAgent: 'EventAgent',
      impactMetrics: { attendees: 220, disruptionScore: 92, utilizationScore: 95 },
    },
    {
      title: 'Final Semester Operating Systems Examination Reschedule',
      type: 'EXAM_RESCHEDULE',
      description: 'Relocate CS301 exam from Room B201 to Seminar Hall A due to social distancing requirement.',
      proposedPlan: {
        planId: 'plan-prop-exam',
        title: 'Plan A: Seminar Hall A (Distance Exam Layout)',
        resourceId: 'SEM-B-01',
        resourceName: 'Seminar Hall A (Sir CV Raman Hall)',
        buildingName: 'Block B (Main Academic & Seminar Complex)',
        capacity: 200,
        feasibilityScore: 95,
        disruptionScore: 84,
        utilizationScore: 80,
        distanceScore: 95,
        decisionScore: 89.2,
        isRecommended: true,
        recommendationReason: 'Provides 2-meter spacing per student with CCTV surveillance coverage.',
        reasons: ['CCTV surveillance active', 'Isolated floor'],
        tradeOffs: ['Displaces 1 elective lecture to B102'],
        requirementsSatisfied: { capacity: true, availability: true, equipment: true, accessibility: true, policyPassed: true },
      },
      requiredRole: 'CAMPUS_ADMIN',
      status: 'PENDING',
      requestedByAgent: 'ScheduleAgent',
      impactMetrics: { attendees: 95, disruptionScore: 84, utilizationScore: 80 },
    },
  ];

  const auditLogs = [
    {
      timestamp: new Date(Date.now() - 3600000 * 2),
      actor: 'Autonomous Engine',
      agent: 'MaintenanceAgent',
      action: 'EMERGENCY_RESOURCE_LOCKOUT',
      reason: 'Critical electrical hazard detected in Lab C1. Resource status set to MAINTENANCE.',
      affectedResources: ['Advanced Computing Lab C1'],
      previousState: 'AVAILABLE',
      newState: 'MAINTENANCE',
      approvalRequired: false,
    },
    {
      timestamp: new Date(Date.now() - 3600000 * 1.5),
      actor: 'ScheduleAgent',
      agent: 'ScheduleAgent',
      action: 'CONFLICT_NOTIFICATION_DISPATCH',
      reason: 'Detected overlap between Guest Lecture and Seminar Hall A booking on tomorrow 14:30.',
      affectedResources: ['Seminar Hall A (Sir CV Raman Hall)'],
      approvalRequired: false,
    },
    {
      timestamp: new Date(Date.now() - 3600000 * 0.8),
      actor: 'Dr. Rajesh Sharma',
      action: 'CAMPUS_AUTONOMY_LEVEL_SET',
      reason: 'Autonomy level updated to Level 2 (Approve then Execute).',
      affectedResources: ['Campus Global Operations'],
      approvalRequired: false,
    },
    {
      timestamp: new Date(Date.now() - 3600000 * 0.4),
      actor: 'ResourceAgent',
      agent: 'ResourceAgent',
      action: 'RESOURCE_RECOVERY_SCAN',
      reason: 'Detected Classroom B204 reserved with 0 telemetry occupancy past grace period.',
      affectedResources: ['Classroom B204'],
      approvalRequired: false,
    },
  ];

  const policyRules = [
    {
      code: 'POL-CAP-01',
      name: 'Strict Capacity Ceiling',
      description: 'A resource cannot accept bookings exceeding its certified physical seat capacity.',
      category: 'CAPACITY',
      isHardConstraint: true,
      isActive: true,
    },
    {
      code: 'POL-MNT-02',
      name: 'Maintenance Safety Lock',
      description: 'Any resource tagged with active maintenance or safety hazard cannot be booked.',
      category: 'MAINTENANCE',
      isHardConstraint: true,
      isActive: true,
    },
    {
      code: 'POL-EXM-03',
      name: 'Examination Governance Approval',
      description: 'Rescheduling or reallocating university exams requires Campus Administrator approval.',
      category: 'GOVERNANCE',
      isHardConstraint: true,
      isActive: true,
    },
    {
      code: 'POL-LGE-04',
      name: 'High-Impact Plenary Review',
      description: 'Allocations exceeding 150 attendees require Human-in-the-Loop authorization.',
      category: 'GOVERNANCE',
      isHardConstraint: true,
      isActive: true,
    },
  ];

  return {
    users,
    buildings,
    resources,
    maintenanceTickets,
    pendingApprovals,
    auditLogs,
    policyRules,
  };
}
